// utils/mou-markdown.ts
// Parses the vendor agreement the server sends (GET /api/vendor/mou).
//
// The text is generated by the web repo's lib/mou-content.ts and only uses
// headings, paragraphs, "- " lists, one table and **bold**. The website
// renders it with a small parser of its own (app/vendor/mou/page.tsx) rather
// than a markdown library; this is the same grammar. Anything else in the
// text is shown as plain text, so a future edit can't hide part of the
// agreement.

/** A run of text, bold or not. */
export interface Inline {
  text: string;
  bold: boolean;
}

export type MouBlock =
  | { type: 'heading'; level: 1 | 2; text: Inline[] }
  /** One entry per source line: the agreement's header puts one fact per line. */
  | { type: 'paragraph'; lines: Inline[][] }
  | { type: 'list'; items: Inline[][] }
  | { type: 'table'; header: string[]; rows: string[][] };

export function parseInline(text: string): Inline[] {
  return text
    .split(/(\*\*[^*]+\*\*)/g)
    .filter((part) => part !== '')
    .map((part) =>
      part.startsWith('**') && part.endsWith('**') && part.length > 4
        ? { text: part.slice(2, -2), bold: true }
        : { text: part, bold: false }
    );
}

const HEADING = /^(#{1,6})\s+(.*)$/;
const isListItem = (line: string) => line.startsWith('- ');
const isTableRow = (line: string) => line.startsWith('|');
const isBlank = (line: string) => line.trim() === '';

const tableCells = (line: string) =>
  line
    .split('|')
    .slice(1, -1)
    .map((cell) => cell.trim());
/** The "| --- | --- |" row between a table's header and its body. */
const isSeparatorRow = (cells: string[]) => cells.length > 0 && cells.every((cell) => /^:?-+:?$/.test(cell));

export function parseMouMarkdown(content: string): MouBlock[] {
  const lines = content.split(/\r?\n/);
  const blocks: MouBlock[] = [];
  let i = 0;

  /** Consumes consecutive lines that match, starting at the current one. */
  const takeWhile = (matches: (line: string) => boolean): string[] => {
    const taken: string[] = [];
    while (i < lines.length && matches(lines[i])) taken.push(lines[i++]);
    return taken;
  };

  while (i < lines.length) {
    const line = lines[i];

    if (isBlank(line)) {
      i++;
      continue;
    }

    const heading = HEADING.exec(line);
    if (heading) {
      blocks.push({ type: 'heading', level: heading[1].length === 1 ? 1 : 2, text: parseInline(heading[2]) });
      i++;
      continue;
    }

    if (isListItem(line)) {
      blocks.push({ type: 'list', items: takeWhile(isListItem).map((item) => parseInline(item.slice(2))) });
      continue;
    }

    if (isTableRow(line)) {
      const [header = [], ...rows] = takeWhile(isTableRow)
        .map(tableCells)
        .filter((cells) => !isSeparatorRow(cells));
      blocks.push({ type: 'table', header, rows });
      continue;
    }

    // A paragraph: this line (whatever it looks like, so the loop always moves
    // forward) and the plain lines after it.
    const paragraph = [lines[i++]];
    paragraph.push(
      ...takeWhile((next) => !isBlank(next) && !HEADING.test(next) && !isListItem(next) && !isTableRow(next))
    );
    blocks.push({ type: 'paragraph', lines: paragraph.map(parseInline) });
  }

  return blocks;
}
